### ISSUE TITLE
Found an error with the error system!

### ISSUE THREAD

**Issue by TheDevConnor** [nkassabian/cedar#2]
Here is the error when we try and get the two lines around the error.
thread 'main' panicked at 'begin <= end (2 <= 1) when slicing `
5
5 ~
5
`', src\error.rs:119:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\kn.exe .\test.cdr` (exit code: 101)

And here is the line it is referring to:
&error_line[find_nth_index(&error_line, '\n', line - 1).unwrap() + 1

**Comment by nkassabian** [comment]
Issue has been fixed!
